### ISSUE TITLE
Using redsys with Node

### ISSUE THREAD

**Issue by ridumai** [santiperez/node-redsys-api#2]
Hi

I have just installed this module to connect to my VPO in my Meteor JS app but I am getting problems. In my server code I have created a new method called from the client. The code in the server looks like this:

`var redsys = new Redsys({
  "merchant": {
    "code": "MERCHANT_CODE",
    "terminal": "1",
    "titular": "TITULAR",
    "name": "NAME",
    "secret": "qwertyasdf0123456789"
  },
  "language": "auto",
  "test": true
});

form_data = redsys.create_payment({
  total: ORDER_TOTAL,
  currency: "EUR",
  order: "ORDER ID",
  description: "ORDER DESCRIPTION",
  data: "CART DATA",
  transaction_type: 0,
  redirect_urls: {
    callback: "CALLBACK URL",
    return_url: "OK URL",
    cancel_url: "KO URL"
  }
});`

I got an error from the server saying that Redsys is not defined. I guess I have to put and import somewhere to make it works but do not know where.

Neither I know where I should put the URL where the form is sent, https://sis-t.redsys.es:25443/sis/realizarPago

I hope someone can help me

**Comment by santiperez** [comment]
Hello,
The require/import is missing at the top.
var Redsys = require('node-redsys-api').Redsys;

Regards
