### ISSUE TITLE
npm audit says base64url should be updated

### ISSUE THREAD

**Issue by glococo** [santiperez/node-redsys-api#4]
Hi buddy,

According to "npm audit", base64url dependency should be updated.
https://nodesecurity.io/advisories/658

Cheers

**Comment by cdelgadob** [comment]
There's a forked repo here which is updated: https://github.com/VonShtirlitz/node-redsys-api

Does anyone knows if this is still working?

**Comment by santiperez** [comment]
Hi,

Thanks @glococo. Version 0.0.5 with the dependencies updated is already available.

Regards
